// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/forge.proto

package forgepb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/types/known/structpb"
)

const Forge_ServiceDescName = "forge.v1.Forge"

type ForgeClient interface {
	SubmitJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	GetJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	CancelJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	GetQueueStats(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	ListDLQ(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
	RequeueDLQ(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error)
}

type forgeClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeClient(cc grpc.ClientConnInterface) ForgeClient {
	return &forgeClient{cc}
}

func (c *forgeClient) SubmitJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/SubmitJob", in, out, opts...)
	return out, err
}

func (c *forgeClient) GetJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/GetJob", in, out, opts...)
	return out, err
}

func (c *forgeClient) CancelJob(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/CancelJob", in, out, opts...)
	return out, err
}

func (c *forgeClient) GetQueueStats(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/GetQueueStats", in, out, opts...)
	return out, err
}

func (c *forgeClient) ListDLQ(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/ListDLQ", in, out, opts...)
	return out, err
}

func (c *forgeClient) RequeueDLQ(ctx context.Context, in *structpb.Struct, opts ...grpc.CallOption) (*structpb.Struct, error) {
	out := new(structpb.Struct)
	err := c.cc.Invoke(ctx, "/forge.v1.Forge/RequeueDLQ", in, out, opts...)
	return out, err
}

type ForgeServer interface {
	SubmitJob(context.Context, *structpb.Struct) (*structpb.Struct, error)
	GetJob(context.Context, *structpb.Struct) (*structpb.Struct, error)
	CancelJob(context.Context, *structpb.Struct) (*structpb.Struct, error)
	GetQueueStats(context.Context, *structpb.Struct) (*structpb.Struct, error)
	ListDLQ(context.Context, *structpb.Struct) (*structpb.Struct, error)
	RequeueDLQ(context.Context, *structpb.Struct) (*structpb.Struct, error)
}

type UnimplementedForgeServer struct{}

func (UnimplementedForgeServer) SubmitJob(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitJob not implemented")
}
func (UnimplementedForgeServer) GetJob(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedForgeServer) CancelJob(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedForgeServer) GetQueueStats(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueueStats not implemented")
}
func (UnimplementedForgeServer) ListDLQ(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDLQ not implemented")
}
func (UnimplementedForgeServer) RequeueDLQ(context.Context, *structpb.Struct) (*structpb.Struct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequeueDLQ not implemented")
}

func RegisterForgeServer(s grpc.ServiceRegistrar, srv ForgeServer) {
	s.RegisterService(&Forge_ServiceDesc, srv)
}

func _Forge_SubmitJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).SubmitJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/SubmitJob"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).SubmitJob(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/GetJob"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).GetJob(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/CancelJob"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).CancelJob(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_GetQueueStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).GetQueueStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/GetQueueStats"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).GetQueueStats(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_ListDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).ListDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/ListDLQ"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).ListDLQ(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

func _Forge_RequeueDLQ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(structpb.Struct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeServer).RequeueDLQ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/forge.v1.Forge/RequeueDLQ"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeServer).RequeueDLQ(ctx, req.(*structpb.Struct))
	}
	return interceptor(ctx, in, info, handler)
}

var Forge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: Forge_ServiceDescName,
	HandlerType: (*ForgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SubmitJob", Handler: _Forge_SubmitJob_Handler},
		{MethodName: "GetJob", Handler: _Forge_GetJob_Handler},
		{MethodName: "CancelJob", Handler: _Forge_CancelJob_Handler},
		{MethodName: "GetQueueStats", Handler: _Forge_GetQueueStats_Handler},
		{MethodName: "ListDLQ", Handler: _Forge_ListDLQ_Handler},
		{MethodName: "RequeueDLQ", Handler: _Forge_RequeueDLQ_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/forge.proto",
}
